### ISSUE TITLE
Backup Bookstackapp & move to storage server

### ISSUE THREAD

**Issue by Alumniminium** [OrigoAT/.github#18]
Bookstackapp (our docs at docs.echovue.ai) currently run on the Dev Server inside CT100.

- [x] Deploy bookstackapp on the Storage Server
- [x] Export the Db of the Dev Server instance
- [x] Import the Db to the Storage Server instance
- [x] Update the Domain Record in the Reverse Proxy to go to the new Instance
- [x] Test & Make sure everything is fine
- [x] Shut down the instance on CT100
- [x] Setup automatic backups on the new instance to /mnt/storage/backups/bookstackapp

**Comment by astomakhinorigo** [comment]
/mnt/storage/bookstackapp contains folders bound as volumes so the db and uploads are already there, I will look later if portainer has any scheduler for periodic container exports or if I have to set it up on the host itself

**Comment by Alumniminium** [comment]
Sorry, was meant to be `/mnt/storage/backups/bookstackapp`
