### ISSUE TITLE
Docker Registry

### ISSUE THREAD

**Issue by Alumniminium** [OrigoAT/.github#25]
A docker container registry already runs on the storage server but it needs access control and configuration.

- [x] redeploy the container with proper configuration
- [x] update ACL in reverse proxy if needed. For now `reg.echovue.ai` requires VPN
  - [x] consider that clients who self-host will need to pull from this
  - [x] #29
- [x] publish all containers from the Backend and Frontend `master` branch to it
- [ ] update the docker-compose.yml in the Backend repo to pull the images from there
- [ ] Setup GitHub Actions that automatically build/publish containers from the `release` branch after pushed

**Comment by astomakhinorigo** [comment]
docker registry runs and http basic authentication is enabled. s3 storage backend is in the conf but somehow the images appear to be stored in the registry but not pushed to s3 with registry container log delivering no errors. One more thing to consider: users should not be able to push to the registry, except for the entitled ones. I did not find the options to set up such granular restrictions for the registry, but according to the logs it seems like push utilizes either PUT, POST or PATCH methods, while pull seems to utilize GET, so if no "native" way is found, it should be filterable through the proxy or firewall

**Comment by Alumniminium** [comment]
so in the reverse proxy we would restrict PUT/POST/PATCH to the VPN and have GET public but with basic auth.
